channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.2.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - absl-py==1.4.0
      - ale-py==0.8.1
      - alembic==1.12.0
      - astunparse==1.6.3
      - atari-py==0.2.6
      - attrs==23.1.0
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.1
      - certifi==2023.7.22
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - chex==0.1.7
      - click==8.1.7
      - cloudpickle==1.6.0
      - colorlog==6.7.0
      - contourpy==1.1.1
      - crafter==1.8.1
      - cycler==0.12.1
      - dataproperty==1.0.1
      - decorator==5.1.1
      - dm-control==1.0.14
      - dm-env==1.6
      - dm-tree==0.1.8
      - farama-notifications==0.0.4
      - filelock==3.12.4
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - fsspec==2023.9.2
      - gast==0.4.0
      - glfw==2.6.2
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.0
      - grpcio==1.56.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h5py==3.9.0
      - huggingface-hub==0.18.0
      - huggingface-sb3==3.0
      - idna==3.4
      - imageio==2.31.1
      - importlib-resources==6.1.0
      - jax==0.4.14
      - jaxlib==0.4.14+cuda11.cudnn86
      - jinja2==3.1.2
      - jsonlines==4.0.0
      - keras==2.13.1
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - libclang==16.0.6
      - lxml==4.9.3
      - mako==1.2.4
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mujoco==2.3.7
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.9.4.25
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - opensimplex==0.4.5
      - opt-einsum==3.3.0
      - optax==0.1.7
      - optuna==3.4.0
      - packaging==23.1
      - pandas==2.1.1
      - pathvalidate==2.5.2
      - pillow==10.0.0
      - protobuf==4.24.0
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.5.2
      - pygments==2.16.1
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pytablewriter==0.64.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rl-zoo3==2.1.0
      - rsa==4.9
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - sb3-contrib==2.1.0
      - scipy==1.11.1
      - setuptools==60.0.0
      - shimmy==1.1.0
      - six==1.16.0
      - sqlalchemy==2.0.22
      - stable-baselines3==2.1.0
      - sympy==1.12
      - tabledata==1.3.3
      - tcolorpy==0.1.4
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow-cpu==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorflow-probability==0.21.0
      - termcolor==2.3.0
      - toolz==0.12.0
      - torch==2.1.0
      - tqdm==4.66.1
      - triton==2.1.0
      - typepy==1.3.2
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - wasabi==1.1.2
      - werkzeug==2.3.6
      - wrapt==1.15.0
